### ISSUE TITLE
install process: reduce mucking with user's machine and enable parallel CI

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#315]
Thanks to @galbramc for input on best practices

 - [x] We should ask for permission to modify the user's `.bashrc` file, (if a modification is necessary* (for CI purposes, the necessary items will already exist in `.bashrc`, so the permission warning won't occur). (Edit: we no longer modify .bashrc or .bash_profile)

 - [x] Add a flag to build.py or setup.py to specify an alternate path/name for `.gpkit`. (Since `.gpkit` needs to be deleted for cvxopt-only testing on linux machines, we are currently in a serial-testing mode for CI. This item, along with #312, will enable parallel testing.

**Comment by bqpd** [comment]
Sounds good! Although `.gpkit` really shouldn't need to be deleted, I agree it should be moveable.

**Comment by galbramc** [comment]
We only have to delete .gpkit so that we can test the cvxopt-only situation. Right now, using mosek actually works on Linux so long as .gpkit/expopt.so exists. Hence I have to delete it to test if the testing assumes mosek is installed when a user only has cvxopt.

**Comment by bqpd** [comment]
Okay. So having gpkit only attempt to use mosek if mosek was found during the install process would solve this issue?

**Comment by galbramc** [comment]
So right now gpkit always finds mosek in the test maching. That is why I have to modify gpkit/env/settings. Similarly, since gpkit finds mosek, it also builds .gpkit/expopt.so. So I have to delete .gpkit/ to prevent a faulty test from using it. Because .gpkit is a "global" thing, a separate test that actually needs to use .gpkit/expopt.so cannot run at the same time as the cvxopt only test that deletes .gpkit/. As a result, the testing is serialized. gpkit is not fundamentally serialized, just the testing.

**Comment by whoburg** [comment]
related to #354

**Comment by whoburg** [comment]
I think this is now resolved thanks to the new `GPKIBUILD` environment var. Feel free to reopen if that is false.
