### ISSUE TITLE
Support signomials being pushed to zero/negative in all algorithms?

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#348]
Users might expect that they can create them! But they can't.

Supersedes / draws from #274 and #336.

**Comment by whoburg** [comment]
What's a zero signomial?

**Comment by bqpd** [comment]
A signomial that will is pushed to 0 in the course of a signomial solve.

**Comment by whoburg** [comment]
is this issue about objectives, constraints, or both?

should it be "zero" or "non positive"?

**Comment by bqpd** [comment]
Both, and the issue occurs when approaching zero.

**Comment by bqpd** [comment]
from #336:

What is the monomial approximation of `s(x) = p1(x)-p2(x)`?

As I understand it, we can take monomial approximations of Posynomials but not of Signomials.

The monomial approximation of `s(x) <= 1` is

```
s(x) <= 1
p1(x) - p2(x) <= 1
p1(x) <= 1 + p2(x)
p1(x)/(1 + p2(x)) <= 1
```

and then we take the monomial approximation of `1 + p2(x)` to form a new Posynomial constraint.

Without a left-hand side, how can we turn subtraction into addition+division?

**Comment by whoburg** [comment]
As suggested in #360, I feel that "we're doin it wrong". Instead of assuming that signomial constraints take the form `s(x) <= 1`, I feel we should assume they take the form `p(x) <= n(x)`, where `p(x)` and `n(x)` are the positive and negative portions of the signomial respectively. The signomial programming heuristic is then to successively approximate `n(x) \approx m_i(x)`, where `m_i(x)` is a monomial, and the signomial constraint is replaced at each iteration with the posynomial constraint `p(x)/m_i(x) <= 1`.

I claim this will solve a lot of problems, including this one.

**Comment by whoburg** [comment]
Unfortunately #360 does not directly lead to a way to optimize zero-valued signomial objectives (nor negative-valued signomial objectives).

I propose leaving this open and moving it to FUTURE.

**Comment by bqpd** [comment]
Sounds good to me. I still feel like the way to support negative value signomials is by adding a large constant to them, or switching their sign :p

**Comment by whoburg** [comment]
Yeah, @pgkirsch discussed this today. One option is to add a large constant to any signomial objective. I worry that this might be sensitive to how large a constant is added.

If one knows a signomial objective takes on a positive value, it can be transformed to a constraint in the usual way:

`minimize p(x) - n(x)`
becomes
```
minimize    t
subject to  n(x) + t >= p(x)
```

And, if one knows the signomial takes on a negative value in advance, I think it's even nicer:

```
minimize    1/t   # (maximize t)
subject to  n(x) >= t + p(x)
```

So `t` lands on the posynomial side in this case, which is nice.

The problem is this relies on knowing in advance whether the optimal objective value is positive or negative. It's therefore also unclear how zee signomials would work. Signomial equality constraints are probably related somehow.

I worry we're missing some (obvious in hindsight) trick that would make all of this work nicely, but I admit I haven't found such a trick yet.

**Comment by whoburg** [comment]
PS -- untested, but I think #360 did cause us to support zero-valued signomials as constraints. the remaining issue is just with objectives.

**Comment by bqpd** [comment]
Agreed!

**Comment by bqpd** [comment]
Closing this; we don't plan to support negative objectives though we might want to document at some point that you can add a large constant to drive an objective negative.
