### ISSUE TITLE
Document verbosity levels

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#449]
re https://github.com/convexopt/gpkit/commit/a81d4089d605ddf07ce910e56502c98d68c4dd18

**Comment by whoburg** [comment]
:thumbsup:

**Comment by whoburg** [comment]
Adding some scope:

 - [ ] document the levels re a81d408
 - [ ] add level between nothing and solution table, to print summary info
 - [ ] in printing logic, instead of accessing `verbosity` directly, use keyword args like `print_time` and `print_table`, and have a simple clear separate function to derive these from verbosity level -- should be clearer and easier to change.

**Comment by bqpd** [comment]
I disagree with item 1. I think printing just a solution table is more useful than printing just timing. (it's a weak preference, but we can't have both)

**Comment by whoburg** [comment]
Re: "When you do want timing info and not the table", the one use case I can think of would be a large model that takes awhile to solve -- might want a summary and timing info, but might not want a mile of table text...

**Comment by bqpd** [comment]
That's true, if the very large model doesn't use vector vars its table output will be unwieldy...

**Comment by whoburg** [comment]
@bqpd here:

Verbosity numbers (and maybe strings) map to default sets, but you can also input a set of the names of the things you want to print.
