### ISSUE TITLE
Document modular models / dynamic/static performance models

### ISSUE THREAD

**Issue by bqpd** [hoburg/gpkit#537]

**Comment by whoburg** [comment]
also document the following (as described by @bqpd):

Right now it's not safe to use the same ConstraintSet in multiple models. (this isn't the only case where it's unsafe; fundamentally this is because ConstraintSet.sub modifies in place instead of returning a new ConstraintSet). This isn't new to the refactor.

**Comment by bqpd** [comment]
The above issues are no longer true.

**Comment by whoburg** [comment]
changed title since our best practices have changed

**Comment by bqpd** [comment]
I think this is closed by #953?

**Comment by whoburg** [comment]
yes, that seems right.
