### ISSUE TITLE
Variables with Margins

### ISSUE THREAD

**Issue by mjburton11** [hoburg/gpkit#901]
@bqpd I have a proposal.  Can we have Variable have a margin attribute? The idea is to have each variable have a margin built in so anywhere it is used the margin is automatically applied.

**Comment by bqpd** [comment]
What is a margin?

**Comment by mjburton11** [comment]
It is a percentage increase on the value of a variable that accounts for uncertainty.  For example, if I  know that currently my avionics weighs 6 lbs, but I might have underestimated estimated the weight on a few things so I will add a 20% margin which would add 1.2 lbs.

**Comment by mjburton11** [comment]
I am currently doing it like this: 
For a margin on BSFC
I have two variable 
`m_fac = Variable(...)`
`BSFC = Variable(...)`
 I have to put `m_fac` everywhere `BSFC` exists in order to capture it's sensitivity to the objective right?

**Comment by 1ozturkbe** [comment]
Here's an idea. What if GpKit automatically created a new variable called m_factor_[variablename], and automatically divided all instances of that variable in constraints with that factor. That way you can get sensitivities to both the variable and its margin.

**Comment by 1ozturkbe** [comment]
i just had a revelation as i was biking to class. the sensitivity to the margin would be exactly the same as the sensitivity to the margin. mike, am i wrong?

**Comment by mjburton11** [comment]
Yes, except that we want this for non-fixed variables.

**Comment by 1ozturkbe** [comment]
That is exactly the point. By getting the sensitivity to the margin, you get the sensitivity to the variable.

**Comment by mjburton11** [comment]
Yes, that is correct.

**Comment by 1ozturkbe** [comment]
K, glad we are on the same page :P

**Comment by mjburton11** [comment]
Ok, Woody just dropped by and explained that adding margin to every variable actually doesn't make sense.  Because by definition free variables have sensitivities of zero.  In fact we tried this we BSFC.  We added margin everywhere BSFC showed up and it actually turned out to be 0.  So for now, we will assume that adding margin in places where the free variable is pressuring down is the best way to go.

**Comment by whoburg** [comment]
yeah, I think the type of margin being discussed in this ticket is best thought of as a margin on a model or on a constraint (as opposed to on a variable). For example, if we have uncertainty in the model for BSFC, which might have the form

```BSFC >= posynomial```,

then it would make sense to add a margin factor to that constraint only, causing the model to predict a higher BSFC. It does not make sense to change the constraint

```m_dot_fuel*g = BSFC*P_shaft```, because that's just a definition and shouldn't get margin.

This works for models for drag, weight, efficiency, etc. The key thing is that the margin gets applied to a model we are uncertain about.

One way to think about the margin factor is like the slack for a RelaxAllConstraintsEqually, just applied in reverse:

```BSFC >= mfac*(posynomial)```
is equivalent to 
```BSFC*s >= (posynomial)```
where `mfac = 1/s`.

**Comment by whoburg** [comment]
@bqpd, the last bit of my post above is why I've been harping on dropping the constraint `s >= 1` in that relaxation formulation.

**Comment by bqpd** [comment]
Hmm, but don't you only care about margins that make things harder? (`s >= 1`)

**Comment by bqpd** [comment]
My only objection to removing that constraint for `RelaxAllConstraintsEqually` is that it makes it dissimilar to `RelaxAllConstraints`
