### ISSUE TITLE
m.debug() and SPs

### ISSUE THREAD

**Issue by mayork** [hoburg/gpkit#945]
m.debug() needs to have a flag where it calls localsolve for SPs

**Comment by bqpd** [comment]
This was semi intentional, actually; it's not clear that the same approach
should be followed for SPs? But thinking on it again now, it seems like
implementing this is the right thing to do, and if it causes issues we'll
learn about them faster this way.

On Nov 14, 2016 3:52 PM, "mayork" <notifications@github.com> wrote:

m.debug() needs to have a flag where it calls localsolve for SPs

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hoburg/gpkit/issues/945>, or mute the thread

**Comment by 1ozturkbe** [comment]
Just to be clear, if m.debug() would be applied to SPs, it would be applied to the first GP approximation of the SP formulation? 

Because if so, it might make sense to have a better way of integrating initial guesses into the variables involved in signomial relations. One way might be to create a new variables attribute called x0? I think that such a capability might be more important as our models get bigger and take more GP solves.

**Comment by bqpd** [comment]
We already have that variable attribute! It's called `sp_init`

**Comment by 1ozturkbe** [comment]
Great to know :P But again to the first question, m.debug() applies to the first GP approx, right?

**Comment by bqpd** [comment]
It could, or to the first GP approx which is primal / dual infeasible. Or it could do what it does with GPs, and modify the SP to have relaxed constants and bounded variables.

**Comment by bqpd** [comment]
@1ozturkbe, this is implemented on the `fix945` branch, try it out!

**Comment by whoburg** [comment]
which version is implemented, in terms of which GP approximation gets debugged?

**Comment by bqpd** [comment]
All of them. The way I implemented it is for `Bounded.as_gpconstr` to return a `Bounded` of the gp-constraint approximations
