### ISSUE TITLE
GP and SP solutions don't do keymapping

### ISSUE THREAD

**Issue by whoburg** [hoburg/gpkit#993]
Consider the following simple Model, which is an SP.

```python
x = Variable("x")
y = Variable("y")
with SignomialsEnabled():
    sig = (y + 6*x >= 13 + x**2)
m = Model(y, [sig])
```

The following things produce valid output:
```python
m.localsolve()("x")
m.localsolve()(x)
m.sp().localsolve()
m.sp().localsolve().table()
m.sp().localsolve()(x)
```
... but `m.sp().localsolve()("x")` results in `ValueError: no variable 'x' found in the solution`.

**Comment by bqpd** [comment]
This is working as intended, but I'm open to changing it. Right now SP and GPs return solution tables of `FastKeyDict`s to save a bit of time. I don't think we should have SPs return `KeyDict`s without GPs doing so, and I don't think we can have GPs doing so until there's a way to reuse the mapping of a `KeyDict` so that we don't recreate it for every sweep etc.

**Comment by whoburg** [comment]
ok got it, thanks. I agree with the current design.

I thought I had seen a mismatch between the keymapping behavior of a GP and an SP in a previous terminal session (where m.program.gps[0].result("x") existed), but I think I've just convinced myself that I was incorrect about that.

**Comment by bqpd** [comment]
I think we should figure out the mapping reuse as mentioned above eventually, though!

**Comment by whoburg** [comment]
e.g. maybe `SolutionArray.__call__` lazily builds the keymap?
